/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.ItemEntrada;
import br.unigran.interfaces.controllers.ItemEntradaController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vanes
 */
public class PainelItemEntrada extends javax.swing.JPanel {

    /**
     * Creates new form PainelItemEntrada
     */
    public PainelItemEntrada() {
        initComponents();
            carregarTabela();

    }
    private void carregarTabela() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Quantidade");
    modelo.addColumn("Custo Unitário");
    modelo.addColumn("Subtotal");
    modelo.addColumn("Id Entrada");
    modelo.addColumn("Id Movimentação");

    List<ItemEntrada> itens = ItemEntradaController.listarTodos();

    for (ItemEntrada i : itens) {
        Integer idEntrada = null;
        Integer idMov = null;

        if (i.getEntradaProduto() != null) {
            idEntrada = i.getEntradaProduto().getId();
        }

        if (i.getMovEstq() != null) {
            idMov = i.getMovEstq().getId();
        }

        modelo.addRow(new Object[]{
            i.getId(),
            i.getQuantidade(),
            i.getCustoUnitario(),
            i.getSubtotal(),
            idEntrada,
            idMov
        });
    }

    tblItensEntrada.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovoItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensEntrada = new javax.swing.JTable();

        jLabel1.setText("Itens de Entrada");

        btnNovoItem.setText("Novo Item");
        btnNovoItem.addActionListener(this::btnNovoItemActionPerformed);

        tblItensEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItensEntrada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(btnNovoItem)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoItem)
                    .addComponent(jLabel1))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoItemActionPerformed
    CadastroItemEntrada tela = new CadastroItemEntrada(null, true);
    tela.setLocationRelativeTo(null);
    tela.setVisible(true);

    carregarTabela();    }//GEN-LAST:event_btnNovoItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItensEntrada;
    // End of variables declaration//GEN-END:variables
}
