/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.PermissaoUsuario;
import br.unigran.interfaces.controllers.PermissaoUsuarioController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanes
 */
public class PainelPermissaoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PainelPermissaoUsuario
     */
    public PainelPermissaoUsuario() {
        initComponents();
        carregarTabela();

    }
    private void carregarTabela() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Usuário");
    modelo.addColumn("Cadastrado por");
    modelo.addColumn("Tipo");
    modelo.addColumn("Data");

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    List<PermissaoUsuario> permissoes =
            PermissaoUsuarioController.listarTodos();

    for (PermissaoUsuario p : permissoes) {
        String usuario = "";
        String usuarioCadastro = "";
        String tipo = "";
        String data = "";

        if (p.getUsuarioCadastrado() != null) {
            usuario = p.getUsuarioCadastrado().getNome();
        }

        if (p.getUsuarioCadastro() != null) {
            usuarioCadastro = p.getUsuarioCadastro().getNome();
        }

        if (p.getTipoPermissoes() != null) {
            tipo = p.getTipoPermissoes().getNome();
        }

        if (p.getDataCadastro() != null) {
            data = sdf.format(p.getDataCadastro());
        }

        modelo.addRow(new Object[]{
            p.getId(),
            usuario,
            usuarioCadastro,
            tipo,
            data
        });
    }

    tblPermissoes.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPermissoes = new javax.swing.JTable();

        jLabel1.setText("Permissões dos Usuários");

        jButton1.setText("Nova Permissão");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tblPermissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPermissoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 CadastroPermissaoUsuario tela = new CadastroPermissaoUsuario(null, true);
    tela.setLocationRelativeTo(null);
    tela.setVisible(true);

    carregarTabela();    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPermissoes;
    // End of variables declaration//GEN-END:variables
}
