/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.Venda;
import br.unigran.interfaces.controllers.VendaController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanes
 */
public class PainelVendas extends javax.swing.JPanel {

    /**
     * Creates new form PainelVendas
     */
    public PainelVendas() {
        initComponents();
        setBackground(new java.awt.Color(232, 236, 241));

        tblVendas.setRowHeight(26);
        tblVendas.setShowGrid(false);
        tblVendas.setSelectionBackground(new java.awt.Color(204, 229, 255));
        tblVendas.setSelectionForeground(java.awt.Color.BLACK);
        carregarTabela();

    }

    private void carregarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Usuário");
        modelo.addColumn("Valor Total");
        modelo.addColumn("Data");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        List<Venda> vendas = VendaController.listarTodos();

        for (Venda v : vendas) {
            String cliente = "";
            String usuario = "";
            String data = "";

            if (v.getCliente() != null) {
                cliente = v.getCliente().getNome();
            }

            if (v.getUsuario() != null) {
                usuario = v.getUsuario().getNome();
            }

            if (v.getDataVenda() != null) {
                data = sdf.format(v.getDataVenda());
            }

            modelo.addRow(new Object[]{
                v.getId(),
                cliente,
                usuario,
                v.getValorTotal(),
                data
            });
        }

        tblVendas.setModel(modelo);
        
        javax.swing.table.DefaultTableCellRenderer centro =
        new javax.swing.table.DefaultTableCellRenderer();

centro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

tblVendas.getColumnModel().getColumn(0).setCellRenderer(centro);

        tblVendas.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblVendas.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblVendas.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblVendas.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblVendas.getColumnModel().getColumn(4).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovaVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vendas cadastradas");

        btnNovaVenda.setBackground(new java.awt.Color(0, 102, 255));
        btnNovaVenda.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnNovaVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaVenda.setText("+ Nova Venda");
        btnNovaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaVenda.addActionListener(this::btnNovaVendaActionPerformed);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Usuário", "Valor Total", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVendas.setPreferredSize(new java.awt.Dimension(700, 350));
        jScrollPane1.setViewportView(tblVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaVenda)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaVenda)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        CadastroVenda tela = new CadastroVenda(null, true);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);

        carregarTabela();

    }//GEN-LAST:event_btnNovaVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVendas;
    // End of variables declaration//GEN-END:variables
}
