/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.EntradaProduto;
import br.unigran.interfaces.controllers.EntradaProdutoController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vanes
 */
public class PainelEntradaProduto extends javax.swing.JPanel {

    /**
     * Creates new form PainelEntradaProduto
     */
    public PainelEntradaProduto() {
        initComponents();
            carregarTabela();

    }
    private void carregarTabela() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Fornecedor");
    modelo.addColumn("Usuário");
    modelo.addColumn("Valor Total");
    modelo.addColumn("Data");

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    List<EntradaProduto> entradas = EntradaProdutoController.listarTodos();

    for (EntradaProduto e : entradas) {
        String fornecedor = "";
        String usuario = "";
        String data = "";

        if (e.getFornecedor() != null) {
            fornecedor = e.getFornecedor().getNome();
        }

        if (e.getUsuario() != null) {
            usuario = e.getUsuario().getNome();
        }

        if (e.getDataEntrada() != null) {
            data = sdf.format(e.getDataEntrada());
        }

        modelo.addRow(new Object[]{
            e.getId(),
            fornecedor,
            usuario,
            e.getValorTotal(),
            data
        });
    }

    tblEntradas.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovaEntrada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();

        jLabel1.setText("Entradas de Produtos");

        btnNovaEntrada.setText("Nova Entrada");
        btnNovaEntrada.addActionListener(this::btnNovaEntradaActionPerformed);

        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovaEntrada)
                    .addComponent(jLabel1))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovaEntrada)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(130, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaEntradaActionPerformed
    CadastroEntradaProduto tela = new CadastroEntradaProduto(null, true);
    tela.setLocationRelativeTo(null);
    tela.setVisible(true);

    carregarTabela();
    }//GEN-LAST:event_btnNovaEntradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntradas;
    // End of variables declaration//GEN-END:variables
}
