/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.MovimentacaoEstoque;
import br.unigran.interfaces.controllers.MovimentacaoEstoqueController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanes
 */
public class PainelEstoque extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstoque
     */
    public PainelEstoque() {
        initComponents();

        setBackground(new java.awt.Color(232, 236, 241));

        tblEstoque.setRowHeight(26);
        tblEstoque.setShowGrid(false);
        tblEstoque.setSelectionBackground(new java.awt.Color(204, 229, 255));
        tblEstoque.setSelectionForeground(java.awt.Color.BLACK);

        carregarTabela();
    }

    private void carregarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Produto");
        modelo.addColumn("Tipo");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Data");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        List<MovimentacaoEstoque> movimentacoes
                = MovimentacaoEstoqueController.listarTodos();

        for (MovimentacaoEstoque m : movimentacoes) {
            String produto = "";

            if (m.getProduto() != null) {
                produto = m.getProduto().getNome();
            }

            String data = "";

            if (m.getDataMovimentacao() != null) {
                data = sdf.format(m.getDataMovimentacao());
            }

            modelo.addRow(new Object[]{
                m.getId(),
                produto,
                m.getTipo(),
                m.getQuantidade(),
                data
            });
        }

        tblEstoque.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovaMovimentaca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Movimentações de Estoque");

        btnNovaMovimentaca.setBackground(new java.awt.Color(0, 102, 255));
        btnNovaMovimentaca.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaMovimentaca.setText("+ Nova Movimentação");
        btnNovaMovimentaca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaMovimentaca.addActionListener(this::btnNovaMovimentacaActionPerformed);

        tblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Tipo", "Quantidade", "Data"
            }
        ));
        jScrollPane1.setViewportView(tblEstoque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaMovimentaca)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnNovaMovimentaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaMovimentacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMovimentacaActionPerformed
        CadastroMovimentacaoEstoque tela = new CadastroMovimentacaoEstoque(null, true);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);

        carregarTabela();
    }//GEN-LAST:event_btnNovaMovimentacaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaMovimentaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstoque;
    // End of variables declaration//GEN-END:variables
}
