package br.unigran.interfaces.ui.screens;

import br.unigran.domain.entity.Produto;
import br.unigran.interfaces.controllers.ClienteController;
import br.unigran.interfaces.controllers.FornecedorController;
import br.unigran.interfaces.controllers.ProdutoController;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author vanes
 */
public class RelatoriosPanel extends javax.swing.JPanel {

    /**
     * Creates new form RelatoriosPanel
     */
    public RelatoriosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnVendas.setText("Vendas");
        btnVendas.addActionListener(this::btnVendasActionPerformed);

        btnProdutos.setText("Produtos");
        btnProdutos.addActionListener(this::btnProdutosActionPerformed);

        btnFornecedores.setText("Fornecedores");
        btnFornecedores.addActionListener(this::btnFornecedoresActionPerformed);

        btnEstoque.setText("Estoque");
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnProdutos)
                .addGap(74, 74, 74)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnFornecedores)
                .addGap(55, 55, 55)
                .addComponent(btnVendas)
                .addGap(43, 43, 43)
                .addComponent(btnEstoque)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes)
                    .addComponent(btnVendas)
                    .addComponent(btnProdutos)
                    .addComponent(btnFornecedores)
                    .addComponent(btnEstoque))
                .addContainerGap(430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed

        JOptionPane.showMessageDialog(
                this,
                "Total de produtos cadastrados: "
                + ProdutoController.listarTodos().size(),
                "Relatório de Produtos",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        JOptionPane.showMessageDialog(
                this,
                "Total de clientes cadastrados: "
                + ClienteController.listarTodos().size(),
                "Relatório de Clientes",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed

        JOptionPane.showMessageDialog(
                this,
                "Total de fornecedores cadastrados: "
                + FornecedorController.listarTodos().size(),
                "Relatório de Fornecedores",
                JOptionPane.INFORMATION_MESSAGE
        );    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        int total = 0;

        for (Produto produto : ProdutoController.listarTodos()) {
            total += produto.getEstoqueAtual();
        }

        JOptionPane.showMessageDialog(
                this,
                "Quantidade total em estoque: " + total,
                "Relatório de Estoque",
                JOptionPane.INFORMATION_MESSAGE
        );    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed

        JOptionPane.showMessageDialog(
                this,
                "Módulo de vendas em desenvolvimento.",
                "Relatório de Vendas",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnVendasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnVendas;
    // End of variables declaration//GEN-END:variables
}
